# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: ../src/Controller/
    type: attribute

admin_controllers:
    resource: ../src/Controller/Admin/
    type: attribute

admin_burger_file:
    resource: ../src/Controller/Admin/BurgerController.php
    type: attribute

# Rediriger l'accueil vers la page de connexion
home_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_login
        permanent: false

app_admin_complement_index:
    path: /admin/complement/
    controller: App\Controller\Admin\ComplementController::index

app_admin_complement_new:
    path: /admin/complement/new
    controller: App\Controller\Admin\ComplementController::new

app_admin_complement_edit:
    path: /admin/complement/{id}/edit
    controller: App\Controller\Admin\ComplementController::edit
    requirements:
        id: '\d+'

app_admin_complement_delete:
    path: /admin/complement/{id}/delete
    controller: App\Controller\Admin\ComplementController::delete
    methods: [POST]
    requirements:
        id: '\d+'
